### ISSUE TITLE
I get the error "HttpError: Not Found"

### ISSUE THREAD

**Issue by WouterSioen** [daneden/enable-automerge-action#16]
Hi,

first of all thanks for building this project. We've been using it successfully for a while on a project.

On two other projects, I do get this error:

```
(node:1478) UnhandledPromiseRejectionWarning: HttpError: Not Found
    at /home/runner/work/_actions/daneden/enable-automerge-action/v1/dist/index.js:2845:26
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (/home/runner/work/_actions/daneden/enable-automerge-action/v1/dist/index.js:4591:31)
(node:1478) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1478) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The configuration is exactly the same as for the other project where it does work. The configuration looks like this:

```yaml
name: Enable automerge on dependabot PRs

on:
  pull_request_target:

jobs:
  automerge:
    name: 🚀  Enable automerge on dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - name: 🚀  Enable automerge on dependabot PRs
        uses: daneden/enable-automerge-action@v1
        with:
          github-token: ${{ secrets.DEPENDABOT_AUTO_MERGE_PERSONAL_ACCESS_TOKEN }}
```

The Action itself says that it successfully completed, but the above error is outputted in the CLI output.

Any idea why this would work on some projects and not on others?

Best Regards

Wouter
